#!/usr/bin/env python3

import re
import subprocess
import sys
from pathlib import Path

DOC_FILE = Path("AndroSH_Help.md")
SUBCOMMAND_RE = re.compile(r'^\s+([a-z][a-z-]+)\s+(.*)$')


def run_help(*args):
	result = subprocess.run(
		[sys.executable, "main.py", *args, "--help"],
		capture_output=True,
		text=True,
	)
	if result.returncode != 0:
		print(f"Command failed: python main.py {' '.join(args)} --help", file=sys.stderr)
		print(result.stderr, file=sys.stderr)
		sys.exit(result.returncode)
	return result.stdout.rstrip("\n")

def parse_subcommands(help_text):
	commands = {}
	for line in help_text.splitlines():
		match = SUBCOMMAND_RE.match(line)
		if match:
			name, desc = match.group(1), match.group(2).strip()
			commands.setdefault(name, desc)
	return commands

def build_doc(main_help, commands):
	table_rows = "\n".join(f"| `{name}` | {desc} |" for name, desc in commands.items())

	detailed_help = "\n\n".join(
		f"### `python main.py {name}`\n\n```\n{run_help(name)}\n```\n\n---"
		for name in commands
	)

	doc = f"""
# AndroSH Command Line Reference
> [!Tip]
> Complete documentation for all AndroSH commands and subcommands

---

## Main Command

```
{main_help}
```

## Available Subcommands

| Command | Description |
|---------|-------------|
{table_rows}

---

## Detailed Subcommand Help

{detailed_help}

*Documentation automatically generated by GitHub Actions*
"""
	return doc.strip() + "\n"

def main():
	main_help = run_help()
	commands = parse_subcommands(main_help)
	doc = build_doc(main_help, commands)
	DOC_FILE.write_text(doc)

	print(f"[*] Found {len(commands)} subcommands: {', '.join(commands)}")
	print(f"[+] Saved to {DOC_FILE}")

if __name__ == "__main__":
	main()
